"""
Django settings for charity_p project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import environ
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*$_6f)dm2g@!-34yn!d!le&+i5v2h$sgn+r1=et41xgx#4e)e9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://akajiugocharityfoundation.org"]
ALLOWED_HOSTS = ["akajiugocharityfoundation.org"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'charity_app',
    'anymail',
    "django.contrib.sitemaps",
    "django.contrib.sites",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'charity_p.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'core/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'charity_p.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'core/static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

load_dotenv()

# ----------------------
# Email Settings
# ----------------------
EMAIL_BACKEND = "anymail.backends.mailersend.EmailBackend"


DEFAULT_FROM_EMAIL = "info@akajiugocharityfoundation.org"

# Optional admin email
ADMIN_EMAIL = "info@akajiugocharityfoundation.org"

# Anymail MailerSend configuration
ANYMAIL = {
    "MAILERSEND_API_TOKEN": os.getenv("MAILERSEND_API_TOKEN"),
}


# Check if MailerSend API key exists
if not ANYMAIL["MAILERSEND_API_TOKEN"]:
    print("❌ MAILERSEND_API_KEY not found in environment!")
else:
    print("✅ MAILERSEND_API_KEY loaded successfully")

# ----------------------
# Paystack Settings
# ----------------------
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
# PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

if not PAYSTACK_PUBLIC_KEY:
    print("⚠️ PAYSTACK_PUBLIC_KEY not found in environment!")
else:
    print("✅ PAYSTACK_PUBLIC_KEY loaded successfully")

# if not PAYSTACK_SECRET_KEY:
#     print("⚠️ PAYSTACK_SECRET_KEY not found in environment!")
# else:
#     print("✅ PAYSTACK_SECRET_KEY loaded successfully")

# ----------------------
# Site URL
# ----------------------
SITE_URL = "https://akajiugocharityfoundation.org/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"